name: klangvalley4locals
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.1.0+6

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  win32: ^5.14.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.1
  http: ^1.4.0
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  intl: ^0.20.2
  html: ^0.15.6 # Use the version compatible with flutter_html
  flutter_html: ^3.0.0-beta.2
  flutter_inappwebview: ^6.1.5
  shared_preferences: ^2.5.3
  flutter_pdfview: ^1.4.1+1
  flutter_cached_pdfview: ^0.4.3
  flutter_downloader: ^1.12.0
  path_provider: ^2.1.5
  google_mobile_ads: ^6.0.0
  url_launcher: ^6.3.1
  permission_handler: ^12.0.1
  vibration: ^3.1.3
  font_awesome_flutter: ^10.8.0
  package_info_plus: ^8.3.0
  archive: ^4.0.7
  in_app_update: ^4.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/KV4L-Splash-Screen.png

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
